export const data=[
    {
        question:"Which of the following acts as the input of a class-based component?",
        option1:"Class",
        option2:"Props",
        option3:"Factory",
        option4:"Render",
        ans:2,
    },
    {
        question:"Which of the following keyword is used to create a class inheritance?",
        option1:"Create",
        option2:"Inherits",
        option3:"Extend",
        option4:"This",
        ans:3,

    },
    {
        question:"A class is a type of function, but instead of using the keyword function to initiate it, which keyword do we use?",
        option1:"Constructor",
        option2:"Class",
        option3:"Object",
        option4:"DataObject",
        ans:2,
    },
    {
        question:"What is the default port where webpack-server runs?",
        option1:"3000",
        option2:"8080",
        option3:"3030",
        option4:"6060",
        ans:2,
        },
        {
            question:" How many numbers of elements a valid react component can return?",
            option1:"1",
            option2:"2",
            option3:"4",
            option4:"5",
            ans:1,
        },
        {
            question:"How many ways of defining your variables in ES6?",
            option1:"1",
            option2:"2",
            option3:"4",
            option4:"5",
            ans:2,
        },
        {
            question:"What are the two ways to handle data in React?",
            option1:"State & Props",
            option2:"Services & Components",
            option3:"State & Services",
            option4:"State & Component",
            ans:1,
        },
        {
            question:"Does React.js create a VIRTUAL DOM in the memory?",
            option1:"TRUE",
            option2:"FALSE",
            option3:"Can be true or false",
            option4:"Cannot say",
            ans:1,
        },
        {
            question:"What does ES6 stand for?",
            option1:"ECMAScript 6",
            option2:"ECMA 6",
            option3:"ECMAJavaScript 6",
            option4:"EJavaScript 6",
            ans:1,
        },
        {
            question:"Which of the following method refers to the parent class in React.js?",
            option1:"inherits()",
            option2:"self()",
            option3:"super()",
            option4:"this()",
            ans:3,
        },

];